#before_script:
#  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
stages:
  - test
#  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
Test:
  stage: test
  script:
   - powershell ./build.ps1 -Tasks Pester
  except:
    - master
#Release:
#  stage: release
#  script:
#   - .\build.ps1 -Tasks 'analyze','test','release'
#  only:
#    - master
