# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NugetApiKey:
    secure: 7b6a0ad7-d512-41db-aaa9-5bd326ee3bf6

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated (package|gruntfile|readme|doc).*|update (package|gruntfile|readme|doc).*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1